name: Bug Report
description: Game crashed or something is not working properly.
title: "[Bug] "
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduce
            description: Please tell us the steps needed in order to recreate your bug.
            value: |
                1.
                2.
                3.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Expected Result
            description: Instead of encountering the bug, what are you expecting instead?
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Modloader
            description: Which modloader were you using?
            options:
                - "Fabric"
                - "Quilt"
                - "Minecraft Forge"
                - "NeoForge"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when encountering this bug
            options:
                - "1.20.5"
                - "1.20.4"
                - "1.19.4"
                - "1.18.2"
                - "1.17.1"
                - "1.16.5"
        validations:
            required: true
    -   type: input
        attributes:
            label: JCM Version
            description: Please enter the version of JCM you were using when encountering this bug (e.g. 2.0.0)
        validations:
            required: true
    -   type: input
        attributes:
            label: MTR Version
            description: This mod is dependent on the MTR Mod, a wrong version of MTR mod could result in unexpected behaviors. 
        validations:
            required: true
    -   type: input
        attributes:
            label: Operating System
            description: The operating system name & version you were using when encountering this bug (e.g. Windows 11, macOS Sonoma/macOS 14, Debian 12)
            placeholder: Windows 11
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Crash Report or Log
            description: If applicable, you can upload the crash report and game logs here (Either with external services like Pastebin, or just drag and drop your file into this text box)
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Extra Informations
            description: If you have noticed any other odd behaviors that may be causing this, please fill it here.
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thanks for reporting! Note that further enquiries may be made on this issue if necessary to identify the issue."